// Information of LRS circuit for the CircDescriptor
pub const NUM_PUB_IO_LRS_SE: usize = 2;
pub const NUM_COMMIT_WITNESS_LRS_SE: usize = 1;
pub const IOPUTS_NAME_LRS_SE : [&str; 4] = [
    "main.sc",
    "main.L",
    "main.phi",
    "main.sk",
];
pub const PATH_PREFIX_LRS_SE: &str = "./circoms/lrs/";
pub const CIRCUIT_NAME_LRS_SE: &str = "lrs";



pub const CIRCUIT_NAME_SCHNORR_VERIFY: &str = "schnorr_verify";

pub const NUM_PUB_IO_LRS_A: usize = 7;
pub const NUM_COMMIT_WITNESS_LRS_A: usize = 0;
pub const IOPUTS_NAME_LRS_A_10: [&str; 31] = [
    "main.root",
    "main.sc",
    "main.L",
    "main.msg",
    "main.R[0]",
    "main.R[1]",
    "main.s",
    "main.sk",
    "main.pk[0]",
    "main.pk[1]",
    "main.phi",
    "main.pathElements[0]",
    "main.pathElements[1]",
    "main.pathElements[2]",
    "main.pathElements[3]",
    "main.pathElements[4]",
    "main.pathElements[5]",
    "main.pathElements[6]",
    "main.pathElements[7]",
    "main.pathElements[8]",
    "main.pathElements[9]",
    "main.pathIndices[0]",
    "main.pathIndices[1]",
    "main.pathIndices[2]",
    "main.pathIndices[3]",
    "main.pathIndices[4]",
    "main.pathIndices[5]",
    "main.pathIndices[6]",
    "main.pathIndices[7]",
    "main.pathIndices[8]",
    "main.pathIndices[9]",
];
pub const IOPUTS_NAME_LRS_A_11: [&str; 33] = [
    "main.root",
    "main.sc",
    "main.L",
    "main.msg",
    "main.R[0]",
    "main.R[1]",
    "main.s",
    "main.sk",
    "main.pk[0]",
    "main.pk[1]",
    "main.phi",
    "main.pathElements[0]",
    "main.pathElements[1]",
    "main.pathElements[2]",
    "main.pathElements[3]",
    "main.pathElements[4]",
    "main.pathElements[5]",
    "main.pathElements[6]",
    "main.pathElements[7]",
    "main.pathElements[8]",
    "main.pathElements[9]",
    "main.pathElements[10]",
    "main.pathIndices[0]",
    "main.pathIndices[1]",
    "main.pathIndices[2]",
    "main.pathIndices[3]",
    "main.pathIndices[4]",
    "main.pathIndices[5]",
    "main.pathIndices[6]",
    "main.pathIndices[7]",
    "main.pathIndices[8]",
    "main.pathIndices[9]",
    "main.pathIndices[10]",
];
pub const IOPUTS_NAME_LRS_A_12: [&str; 35] = [
    "main.root",
    "main.sc",
    "main.L",
    "main.msg",
    "main.R[0]",
    "main.R[1]",
    "main.s",
    "main.sk",
    "main.pk[0]",
    "main.pk[1]",
    "main.phi",
    "main.pathElements[0]",
    "main.pathElements[1]",
    "main.pathElements[2]",
    "main.pathElements[3]",
    "main.pathElements[4]",
    "main.pathElements[5]",
    "main.pathElements[6]",
    "main.pathElements[7]",
    "main.pathElements[8]",
    "main.pathElements[9]",
    "main.pathElements[10]",
    "main.pathElements[11]",
    "main.pathIndices[0]",
    "main.pathIndices[1]",
    "main.pathIndices[2]",
    "main.pathIndices[3]",
    "main.pathIndices[4]",
    "main.pathIndices[5]",
    "main.pathIndices[6]",
    "main.pathIndices[7]",
    "main.pathIndices[8]",
    "main.pathIndices[9]",
    "main.pathIndices[10]",
    "main.pathIndices[11]",
];
pub const IOPUTS_NAME_LRS_A_13: [&str; 37] = [
    "main.root",
    "main.sc",
    "main.L",
    "main.msg",
    "main.R[0]",
    "main.R[1]",
    "main.s",
    "main.sk",
    "main.pk[0]",
    "main.pk[1]",
    "main.phi",
    "main.pathElements[0]",
    "main.pathElements[1]",
    "main.pathElements[2]",
    "main.pathElements[3]",
    "main.pathElements[4]",
    "main.pathElements[5]",
    "main.pathElements[6]",
    "main.pathElements[7]",
    "main.pathElements[8]",
    "main.pathElements[9]",
    "main.pathElements[10]",
    "main.pathElements[11]",
    "main.pathElements[12]",
    "main.pathIndices[0]",
    "main.pathIndices[1]",
    "main.pathIndices[2]",
    "main.pathIndices[3]",
    "main.pathIndices[4]",
    "main.pathIndices[5]",
    "main.pathIndices[6]",
    "main.pathIndices[7]",
    "main.pathIndices[8]",
    "main.pathIndices[9]",
    "main.pathIndices[10]",
    "main.pathIndices[11]",
    "main.pathIndices[12]",
];
pub const IOPUTS_NAME_LRS_A_14: [&str; 39] = [
    "main.root",
    "main.sc",
    "main.L",
    "main.msg",
    "main.R[0]",
    "main.R[1]",
    "main.s",
    "main.sk",
    "main.pk[0]",
    "main.pk[1]",
    "main.phi",
    "main.pathElements[0]",
    "main.pathElements[1]",
    "main.pathElements[2]",
    "main.pathElements[3]",
    "main.pathElements[4]",
    "main.pathElements[5]",
    "main.pathElements[6]",
    "main.pathElements[7]",
    "main.pathElements[8]",
    "main.pathElements[9]",
    "main.pathElements[10]",
    "main.pathElements[11]",
    "main.pathElements[12]",
    "main.pathElements[13]",
    "main.pathIndices[0]",
    "main.pathIndices[1]",
    "main.pathIndices[2]",
    "main.pathIndices[3]",
    "main.pathIndices[4]",
    "main.pathIndices[5]",
    "main.pathIndices[6]",
    "main.pathIndices[7]",
    "main.pathIndices[8]",
    "main.pathIndices[9]",
    "main.pathIndices[10]",
    "main.pathIndices[11]",
    "main.pathIndices[12]",
    "main.pathIndices[13]",
];
pub const IOPUTS_NAME_LRS_A_15: [&str; 41] = [
    "main.root",
    "main.sc",
    "main.L",
    "main.msg",
    "main.R[0]",
    "main.R[1]",
    "main.s",
    "main.sk",
    "main.pk[0]",
    "main.pk[1]",
    "main.phi",
    "main.pathElements[0]",
    "main.pathElements[1]",
    "main.pathElements[2]",
    "main.pathElements[3]",
    "main.pathElements[4]",
    "main.pathElements[5]",
    "main.pathElements[6]",
    "main.pathElements[7]",
    "main.pathElements[8]",
    "main.pathElements[9]",
    "main.pathElements[10]",
    "main.pathElements[11]",
    "main.pathElements[12]",
    "main.pathElements[13]",
    "main.pathElements[14]",
    "main.pathIndices[0]",
    "main.pathIndices[1]",
    "main.pathIndices[2]",
    "main.pathIndices[3]",
    "main.pathIndices[4]",
    "main.pathIndices[5]",
    "main.pathIndices[6]",
    "main.pathIndices[7]",
    "main.pathIndices[8]",
    "main.pathIndices[9]",
    "main.pathIndices[10]",
    "main.pathIndices[11]",
    "main.pathIndices[12]",
    "main.pathIndices[13]",
    "main.pathIndices[14]",
];
pub const IOPUTS_NAME_LRS_A_16: [&str; 43] = [
    "main.root",
    "main.sc",
    "main.L",
    "main.msg",
    "main.R[0]",
    "main.R[1]",
    "main.s",
    "main.sk",
    "main.pk[0]",
    "main.pk[1]",
    "main.phi",
    "main.pathElements[0]",
    "main.pathElements[1]",
    "main.pathElements[2]",
    "main.pathElements[3]",
    "main.pathElements[4]",
    "main.pathElements[5]",
    "main.pathElements[6]",
    "main.pathElements[7]",
    "main.pathElements[8]",
    "main.pathElements[9]",
    "main.pathElements[10]",
    "main.pathElements[11]",
    "main.pathElements[12]",
    "main.pathElements[13]",
    "main.pathElements[14]",
    "main.pathElements[15]",
    "main.pathIndices[0]",
    "main.pathIndices[1]",
    "main.pathIndices[2]",
    "main.pathIndices[3]",
    "main.pathIndices[4]",
    "main.pathIndices[5]",
    "main.pathIndices[6]",
    "main.pathIndices[7]",
    "main.pathIndices[8]",
    "main.pathIndices[9]",
    "main.pathIndices[10]",
    "main.pathIndices[11]",
    "main.pathIndices[12]",
    "main.pathIndices[13]",
    "main.pathIndices[14]",
    "main.pathIndices[15]",
];
pub const PATH_PREFIX_LRS_A: &str = "./circoms/lrs_a/lrs_a/lrs_a_circoms/";
pub const CIRCUIT_NAME_LRS_A_10: &str = "lrs_a_10";
pub const CIRCUIT_NAME_LRS_A_11: &str = "lrs_a_11";
pub const CIRCUIT_NAME_LRS_A_12: &str = "lrs_a_12";
pub const CIRCUIT_NAME_LRS_A_13: &str = "lrs_a_13";
pub const CIRCUIT_NAME_LRS_A_14: &str = "lrs_a_14";
pub const CIRCUIT_NAME_LRS_A_15: &str = "lrs_a_15";
pub const CIRCUIT_NAME_LRS_A_16: &str = "lrs_a_16";

pub const NUM_PUB_IO_LRS_B: usize = 14;
pub const NUM_COMMIT_WITNESS_LRS_B: usize = 1;
pub const IOPUTS_NAME_LRS_B: [&str; 19] = [
    "main.sc",
    "main.L",
    "main.c[0][0]",
    "main.c[0][1]",
    "main.c[0][2]",
    "main.c[0][3]",
    "main.c[0][4]",
    "main.c[0][5]",
    "main.c[1][0]",
    "main.c[1][1]",
    "main.c[1][2]",
    "main.c[1][3]",
    "main.c[1][4]",
    "main.c[1][5]",
    "main.phi",
    "main.sk",
    "main.pk[0]",
    "main.pk[1]",
    "main.r",
];
pub const PATH_PREFIX_LRS_B: &str = "./circoms/lrs_b/";
pub const CIRCUIT_NAME_LRS_B: &str = "lrs_b";
